# Generated by Django 5.2.3 on 2025-06-24 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_time', models.DateTimeField(auto_now_add=True)),
                ('reward_penalty', models.PositiveIntegerField(default=0)),
                ('time_before_booking', models.DurationField()),
                ('reason', models.TextField(blank=True, default='User cancelled')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_log', to='booking.booking')),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Cancellation',
                'verbose_name_plural': 'Booking Cancellations',
                'ordering': ['-cancellation_time'],
            },
        ),
    ]
