# Generated by Django 5.2.3 on 2025-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reward_change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
