# Generated by Django 5.2.3 on 2025-06-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_reward_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reward_change',
            new_name='reward_points',
        ),
    ]
