# Generated by Django 5.2.3 on 2025-06-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_reward_change_customuser_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
