# Generated by Django 5.2.3 on 2025-06-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hours_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_booking',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
