# Generated by Django 5.2.3 on 2025-06-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_hours_played_customuser_total_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hours_played',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_booking',
        ),
    ]
